name: smai
description: SMAI - New way of thinking about social media
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  html: ^0.15.0
  cached_network_image: ^3.2.0
  permission_handler: ^9.0.0
  http: ^0.13.3
  path_provider: ^2.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  firebase_core_web: ^2.7.0
  firebase_auth_web: ^5.6.3
  cloud_firestore: ^3.1.10
  provider: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/